// <auto-generated />
using System;
using DATABASE.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TeaShopDAL.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20220319154840_LinkToPhoto")]
    partial class LinkToPhoto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DATABASE.Entityes.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderId"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<bool>("OrderStatus")
                        .HasColumnType("bit");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptMethod")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DATABASE.Entityes.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProductCount")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductPathToImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DATABASE.Entityes.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"), 1L, 1);

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            ChatId = 444343256L,
                            CreatedAt = new DateTime(2022, 3, 19, 15, 48, 39, 717, DateTimeKind.Utc).AddTicks(8947),
                            IsAdmin = true,
                            IsDeleted = false,
                            Name = "noncredistka"
                        },
                        new
                        {
                            UserId = 2L,
                            ChatId = 519140043L,
                            CreatedAt = new DateTime(2022, 3, 19, 15, 48, 39, 717, DateTimeKind.Utc).AddTicks(8951),
                            IsAdmin = true,
                            IsDeleted = false,
                            Name = "shanti_travels"
                        });
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.Property<long>("OrdersOrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductsProductId")
                        .HasColumnType("bigint");

                    b.HasKey("OrdersOrderId", "ProductsProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("DATABASE.Entityes.Herb", b =>
                {
                    b.HasBaseType("DATABASE.Entityes.Product");

                    b.Property<int>("Region")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.ToTable("Herbs");
                });

            modelBuilder.Entity("DATABASE.Entityes.Honey", b =>
                {
                    b.HasBaseType("DATABASE.Entityes.Product");

                    b.Property<int>("HoneyWeight")
                        .HasColumnType("int");

                    b.ToTable("Honey");
                });

            modelBuilder.Entity("DATABASE.Entityes.Tea", b =>
                {
                    b.HasBaseType("DATABASE.Entityes.Product");

                    b.Property<int>("TeaForm")
                        .HasColumnType("int");

                    b.Property<int>("TeaType")
                        .HasColumnType("int");

                    b.Property<int>("TeaWeight")
                        .HasColumnType("int");

                    b.ToTable("Teas");
                });

            modelBuilder.Entity("DATABASE.Entityes.Order", b =>
                {
                    b.HasOne("DATABASE.Entityes.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.HasOne("DATABASE.Entityes.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATABASE.Entityes.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DATABASE.Entityes.Herb", b =>
                {
                    b.HasOne("DATABASE.Entityes.Product", null)
                        .WithOne()
                        .HasForeignKey("DATABASE.Entityes.Herb", "ProductId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DATABASE.Entityes.Honey", b =>
                {
                    b.HasOne("DATABASE.Entityes.Product", null)
                        .WithOne()
                        .HasForeignKey("DATABASE.Entityes.Honey", "ProductId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DATABASE.Entityes.Tea", b =>
                {
                    b.HasOne("DATABASE.Entityes.Product", null)
                        .WithOne()
                        .HasForeignKey("DATABASE.Entityes.Tea", "ProductId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DATABASE.Entityes.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
