// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeaShopDAL;

#nullable disable

namespace TeaShopDAL.Migrations
{
    [DbContext(typeof(d7ogg57688h1bbContext))]
    partial class d7ogg57688h1bbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DATABASE.Entityes.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrderId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("OrderStatus")
                        .HasColumnType("boolean");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<int>("ReceiptMethod")
                        .HasColumnType("integer");

                    b.Property<long>("UserChatId")
                        .HasColumnType("bigint");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DATABASE.Entityes.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProductId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("InStock")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductCount")
                        .HasColumnType("integer");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProductPathToImage")
                        .HasColumnType("text");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("numeric");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DATABASE.Entityes.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Firstname")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Lastname")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            ChatId = 444343256L,
                            CreatedAt = new DateTime(2022, 4, 13, 14, 15, 13, 491, DateTimeKind.Utc).AddTicks(8872),
                            Firstname = "nucleus accumbens",
                            IsAdmin = true,
                            IsDeleted = false,
                            Username = "noncredistka"
                        },
                        new
                        {
                            UserId = 2L,
                            ChatId = 519140043L,
                            CreatedAt = new DateTime(2022, 4, 13, 14, 15, 13, 491, DateTimeKind.Utc).AddTicks(8876),
                            Firstname = "Алексей Курлян",
                            IsAdmin = true,
                            IsDeleted = false,
                            Username = "shanti_travels"
                        });
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.Property<long>("OrdersOrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductsProductId")
                        .HasColumnType("bigint");

                    b.HasKey("OrdersOrderId", "ProductsProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("DATABASE.Entityes.Herb", b =>
                {
                    b.HasBaseType("DATABASE.Entityes.Product");

                    b.Property<int>("Region")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.ToTable("Herbs");
                });

            modelBuilder.Entity("DATABASE.Entityes.Honey", b =>
                {
                    b.HasBaseType("DATABASE.Entityes.Product");

                    b.Property<int>("HoneyWeight")
                        .HasColumnType("integer");

                    b.ToTable("Honey");
                });

            modelBuilder.Entity("DATABASE.Entityes.Tea", b =>
                {
                    b.HasBaseType("DATABASE.Entityes.Product");

                    b.Property<int>("TeaForm")
                        .HasColumnType("integer");

                    b.Property<int>("TeaType")
                        .HasColumnType("integer");

                    b.Property<int>("TeaWeight")
                        .HasColumnType("integer");

                    b.ToTable("Teas");
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.HasOne("DATABASE.Entityes.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATABASE.Entityes.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DATABASE.Entityes.Herb", b =>
                {
                    b.HasOne("DATABASE.Entityes.Product", null)
                        .WithOne()
                        .HasForeignKey("DATABASE.Entityes.Herb", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DATABASE.Entityes.Honey", b =>
                {
                    b.HasOne("DATABASE.Entityes.Product", null)
                        .WithOne()
                        .HasForeignKey("DATABASE.Entityes.Honey", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DATABASE.Entityes.Tea", b =>
                {
                    b.HasOne("DATABASE.Entityes.Product", null)
                        .WithOne()
                        .HasForeignKey("DATABASE.Entityes.Tea", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
